name: Build ZMK firmware
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'keymap-drawer/**'
      - 'keymap-drawer.yaml'
      - 'Makefile'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'keymap-drawer/**'
      - 'keymap-drawer.yaml'
      - 'Makefile'
      - '.gitignore'
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - 'keymap-drawer/**'
      - 'keymap-drawer.yaml'
      - 'Makefile'
      - '.gitignore'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
